version: '2'
services:
  neo4j:
    image: neo4j:3.5
    environment:
      - neo_data:/data
      - neo_logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"

volumes:
  neo_data: {}
  neo_logs: {}

